version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ev-charging-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ev_charging
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ev-net

networks:
  ev-net:
    driver: bridge

volumes:
  postgres_data:
